name: Tester
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install Request
        run: pip install requests
      - name: Run script
        run: python script.py
